name: banana4life

services:
  valkey:
    image: valkey/valkey:latest@sha256:8436e10bc65c94886a91d4415b6a6dfa9cb5a306fb3b996e5bb67cd2b4854193
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - valkey:/app/data

volumes:
  valkey: