name: banana4life

services:
  valkey:
    image: valkey/valkey:latest@sha256:4963247afc4cd33c7d3b2d2816b9f7f8eeebab148d29056c2ca4d7cbc966f2d9
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - valkey:/app/data

volumes:
  valkey: