name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: "adopt@1.11.0-1"
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Build and Publish
        env:
          JIB_TARGET_IMAGE_USERNAME: ${{ secrets.JIB_TARGET_IMAGE_USERNAME }}
          JIB_TARGET_IMAGE_PASSWORD: ${{ secrets.JIB_TARGET_IMAGE_PASSWORD }}
        run: |
          sbt -v -Dfile.encoding=UTF-8 jibImageBuild
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger Deployment
        uses: appleboy/gitlab-ci-action@v0.0.2
        with:
          host: "https://git.cubyte.org"
          token: ${{ secrets.DEPLOY_TOKEN }}
          ref: master
          project_id: 230
