name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: sbt/setup-sbt@v1
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: sbt
      - name: Build and Publish
        env:
          JIB_TARGET_IMAGE_USERNAME: ${{ github.actor }}
          JIB_TARGET_IMAGE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: sbt -Dplay.env=prod jibImageBuild
      - name: Deploy
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          json="$(jq -c '{"image":{"repository": (.image | split(":")[0]), "tag": (.image | split(":")[1]), digest: .imageDigest}}' < target/jib-image.json)"
          curl -X POST \
            -s \
            --fail \
            -F "token=$DEPLOY_TOKEN" \
            -F "ref=main" \
            -F "variables[TARGET]=website" \
            -F "variables[IMAGE_VALUES]=$json" \
            -F "variables[COMMIT_MESSAGE]=$COMMIT_MESSAGE" \
            https://cubyte.dev/api/v4/projects/373/trigger/pipeline
